Tabs.DPlayer=Window:AddTab('Player') Tabs.DBypass=Window:AddTab('Bypass') Tabs.DVisuals=Window:AddTab('Visuals') Tabs.DFloor=Window:AddTab('Floor')

local ExecutorSupport = loadstring(game:HttpGet("https://raw.githubusercontent.com/TheHunterSolo1/Scripts/refs/heads/main/ExecutorTest"))()
local ESPLibrary      = loadstring(game:HttpGet("https://raw.githubusercontent.com/TheHunterSolo1/Scripts/main/ESPLibrary"))()
local Connections = {}
local Firepp,Require,ReplicateSignal,FireTouch,HookMeta,IsNetworkOwner = ExecutorSupport.fireproximityprompt,ExecutorSupport.require,ExecutorSupport.replicatesignal,ExecutorSupport.firetouchinterest,ExecutorSupport.hookmetamethod,ExecutorSupport.isnetworkowner
repeat task.wait() until localPlayer.Character
local RemotesFolder = ReplicatedStorage:FindFirstChild("EntityInfo") or ReplicatedStorage:FindFirstChild("Bricks") or ReplicatedStorage:FindFirstChild("RemotesFolder")
local Floor       = ReplicatedStorage:WaitForChild("GameData"):WaitForChild("Floor")
local LatestRoom  = ReplicatedStorage:WaitForChild("GameData"):WaitForChild("LatestRoom")
local MainGame    = localPlayer:WaitForChild("PlayerGui"):WaitForChild("MainUI").Initiator:WaitForChild("Main_Game")
local RemoteListener = MainGame:WaitForChild("RemoteListener")
local ClientModules  = ReplicatedStorage:FindFirstChild("ModulesClient") or ReplicatedStorage:FindFirstChild("ClientModules")
local MotorReplication = RemotesFolder:WaitForChild("MotorReplication")
local CamLock     = RemotesFolder:WaitForChild("CamLock")
local PL          = RemotesFolder:WaitForChild("PL")
local CollisionClone, RequiredMainGame
if Require then RequiredMainGame = require(MainGame) end
local CurrentFloor = Floor.Value
local isBricks = RemotesFolder.Name == "Bricks"
local Method = "Legit"

local function GetDistanceToPlayer(Pos) local A=localPlayer.Character and localPlayer.Character:FindFirstChild("HumanoidRootPart") and localPlayer.Character.HumanoidRootPart.Position or camera.CFrame.Position return (A-Pos).Magnitude end
local function AddESP(part,txt,color) ESPLibrary:AddESP({Object=part,Text=txt,Color=color}) end
local function AddEntityESP(part,txt,color) if part:IsA("Model") then while not part.PrimaryPart do for _,v in pairs(part:GetChildren()) do if v:IsA("BasePart") then part.PrimaryPart=v end end task.wait() end if part.PrimaryPart then part.PrimaryPart.Transparency=0.99 end if not part:FindFirstChildOfClass("Humanoid") then Instance.new("Humanoid",part) end end if part.Name=="FigureRig" or part.Name=="FigureRagdoll" then part:WaitForChild("Root").Size=Vector3.new(0.001,0.001,0.001) end ESPLibrary:AddESP({Object=part,Text=txt,Color=color}) end
local function GetLibraryCode() local CL=ReplicatedStorage.GameData.Floor.Value=="Fools" and 10 or 5 local Slot=table.create(CL,"_") local Paper for _,plr in pairs(Players:GetPlayers()) do local char=plr.Character if char then Paper=char:FindFirstChild("LibraryHintPaper") or char:FindFirstChild("LibraryHintPaperHard") or plr.Backpack:FindFirstChild("LibraryHintPaper") or plr.Backpack:FindFirstChild("LibraryHintPaperHard") if Paper then break end end end if not Paper then return table.concat(Slot) end local Hints=localPlayer.PlayerGui.PermUI.Hints:GetChildren() for _,i in pairs(Paper.UI:GetChildren()) do if i:IsA("ImageLabel") and i.Name~="Image" then local Pos=tonumber(i.Name) if Pos and Slot[Pos] then for _,v in pairs(Hints) do if v.Name=="Icon" and v.ImageRectOffset.X==i.ImageRectOffset.X then local L=v:FindFirstChild("TextLabel") if L then Slot[Pos]=L.Text end break end end end end end return table.concat(Slot) end

local PathFolder=Instance.new("Folder",workspace) PathFolder.Name="PathFolder"
local SeekPath=Instance.new("Folder",workspace) SeekPath.Name="SeekPath"
local IsMoving=false
function ShowSeekPath(v) local P=Instance.new("Part",SeekPath) P.Size=Vector3.new(1.5,1.5,1.5) P.Anchored=true P.Shape="Ball" P.Position=v.Position P.CanCollide=false P.Color=Color3.new(0,1,0) Debris:AddItem(P,60) end
function FixBridge(v) for _,i in pairs(v:GetChildren()) do if i.Name=="PlayerBarrier" and i.Rotation.X==180 then local B=i:Clone() B.CFrame=CFrame.new(i.Position.X,i.Position.Y,i.Position.Z)*CFrame.new(0,-7,0) B.Size=Vector3.new(40,0.1,40) B.Transparency=0.5 B.Color=Color3.new(0.5,0,0.5) B.Material="ForceField" B.Parent=v B.Name="BridgeBarrier" B.Anchored=true B.CanCollide=true end end end
function PathTo(Pos) local C=localPlayer.Character local R=C and C:FindFirstChild("HumanoidRootPart") local H=C and C:FindFirstChild("Humanoid") if not R or not H then return end local p=PathfindingService:CreatePath({AgentRadius=2,AgentHeight=5,AgentCanJump=true,WaypointSpacing=2,AgentMaxSlope=45,AgentJumpHeight=0}) p:ComputeAsync(R.Position,Pos+Vector3.new(0,0,1)) if p.Status~=Enum.PathStatus.Success then return end for _,wp in ipairs(p:GetWaypoints()) do if not Toggles.AutoRooms.Value or Library.Unloaded then break end if (R.Position-wp.Position).Magnitude>=2 then H:MoveTo(wp.Position) H.MoveToFinished:Wait() end end end
function Breaker(part) local label=part:WaitForChild("SurfaceGui"):WaitForChild("Frame"):WaitForChild("Code") local function run() task.wait(0.05) if not Toggles.AutoBreaker.Value then return end if Method=="Exploit" then RemotesFolder.EBF:FireServer() return end if Method=="Legit" then local target=tonumber(label.Text) if target then for _,v in part:GetChildren() do if v.Name=="BreakerSwitch" and v:GetAttribute("ID")==target then local trans=part.SurfaceGui.Frame.Code:WaitForChild("Frame").BackgroundTransparency local pc=v:FindFirstChild("PrismaticConstraint") local light=v:FindFirstChild("Light") local sound=v:FindFirstChild("Sound") if trans==0 then if v:GetAttribute("Enabled") then return end v:SetAttribute("Enabled",true) if pc then pc.TargetPosition=-0.2 end if light then light.Material=Enum.Material.Neon local sp=light:FindFirstChild("Spark",true) if sp then sp:Emit(1) end end if sound then sound:Play() end elseif trans==1 then if not v:GetAttribute("Enabled") then return end v:SetAttribute("Enabled",false) if pc then pc.TargetPosition=0.2 end if light then light.Material=Enum.Material.Glass end if sound then sound:Play() end end break end end end end end label:GetPropertyChangedSignal("Text"):Connect(run) run() end

local HidingPlaces={["Wardrobe"]="Closet",["Rooms_Locker"]="Locker",["Rooms_Locker_Fridge"]="Fridge",["Locker_Large"]="Locker",["Backdoor_Wardrobe"]="Closet",["Bed"]="Bed",["Double_Bed"]="Double Bed",["Toolshed"]="Closet",["RetroWardrobe"]="Closet",["CircularVent"]="Vent"}
local Closets={} for _,v in pairs(workspace.CurrentRooms:GetDescendants()) do if HidingPlaces[v.Name] then table.insert(Closets,v) end end
local PromptIgnore={HidePrompt=true,ClimbPrompt=true,PropPrompt=true,InteractPrompt=true,RiftPrompt=true,StarRiftPrompt=true,NoHidingLilBro=true,AnimatePrompt=true,RevivePrompt=true}
local Interactions={} local Stored={} local Figures={} local DuckBoards={} local Nodes={} local Anchors={}
local Names={Lock=true,ChestBoxLocked=true,Cellar=true,Chest_Vine=true,CuttableVines=true,SkullLock=true,Toolbox_Locked=true,Lock1=true,Lock2=true}
local Items={["Bandage"]="Bandage",["Flashlight"]="Flash light",["Battery"]="Battery",["SkeletonKey"]="Skeleton Key",["Crucifix"]="Crucifix",["Lockpick"]="Lockpick",["Vitamins"]="Vitamin",["Shears"]="Shears",["LaserPointer"]="Laser Pointer",["Candle"]="Candle",["StarJug"]="Jug",["StardustPickup"]="Stardust",["ChestBoxLocked"]="Locked Chest",["ChestBox"]="Chest",["HolyGrenade"]="Holy Grenade",["ShieldMini"]="Mini Shield",["ShieldBig"]="Big Shield",["KeyIron"]="Iron Key",["GoldGun"]="Golden Gun",["LibraryHintPaper"]="Hint Paper"}
local roomEntities={["Snare"]="Snare",["FigureRig"]="Figure",["FigureRagdoll"]="Figure",["GrumbleRig"]="Grumble",["Groundskeeper"]="Ground Keeper",["MandrakeLive"]="Man Drake",["LiveEntityBramble"]="Bramble"}
local workspaceEntities={["RushMoving"]="Rush",["AmbushMoving"]="Ambush",["A60"]="A-60",["A120"]="A-120",["GlitchRush"]="Glitch Rush",["GlitchAmbush"]="Glitch Ambush",["Eyes"]="Eyes",["Lookman"]="Eyes",["BackdoorRush"]="Blitz",["BackdoorLookman"]="Lookman",["JeffTheKiller"]="Jeff"}
local DoorColor,HidingPlaceColor,LeverColor=Color3.new(0,1,1),Color3.new(0,0.4,0),Color3.new(0.5,0.5,0.5)
local BookColor,BreakerColor,ItemsColor=Color3.new(0,0,0.5),Color3.new(0.5,1,0.5),Color3.new(1,0.5,1)
local GoldColor,LadderColor,FuseColor=Color3.new(1,1,0),Color3.new(0,0,1),Color3.new(0.2,0.5,0.3)
local EntityColor,PlayerColor=Color3.new(1,0,0),Color3.new(1,1,1)
local OldAccel,OldFogEnd
local Params=RaycastParams.new() Params.FilterType=Enum.RaycastFilterType.Exclude

local function InfPrompt(Prompt) local Char=localPlayer.Character if not Char then return end local Tool=Char:FindFirstChild("Lockpick") or Char:FindFirstChild("SkeletonKey") or Char:FindFirstChild("Shears") local Name=Tool and Tool.Name if Tool then if not Prompt:GetAttribute("InfItems") then Prompt.Enabled=false Prompt:SetAttribute("InfItems",true) Prompt:SetAttribute("Tool",Name) Prompt.ClickablePrompt=false local Clone=Prompt:Clone() Clone.Name="InfPrompt" Clone.MaxActivationDistance=Prompt.MaxActivationDistance*0.5 Clone.Parent=Prompt.Parent Clone.Enabled=true Clone.ClickablePrompt=true local Con Con=Clone.Triggered:Connect(function() Con:Disconnect() Clone:Destroy() if Char:FindFirstChild(Name) then task.spawn(function() local Drop=nil local st=tick() repeat RemotesFolder.DropItem:FireServer(Tool) task.wait(0.01) local cd=15 for _,v in ipairs(workspace.Drops:GetChildren()) do if v.Name==Name then local d=GetDistanceToPlayer(v:GetPivot().Position) if d<cd then cd=d Drop=v end end end until Drop or not Char:FindFirstChild(Name) or (tick()-st)>3 if Drop and Firepp then local dp=Drop:FindFirstChildWhichIsA("ProximityPrompt",true) if dp then fireproximityprompt(dp) end end if Firepp then fireproximityprompt(Prompt) end Prompt:SetAttribute("InfItems",nil) Prompt:SetAttribute("Tool",nil) Prompt.Enabled=true Prompt.ClickablePrompt=true end) else Prompt:SetAttribute("InfItems",nil) Prompt.Enabled=true Prompt.ClickablePrompt=true end end) end end end

-- PLAYER TAB
local PlayerBox=Tabs.DPlayer:AddLeftGroupbox('Player') local AutoBox=Tabs.DPlayer:AddRightGroupbox('Auto') local ReachBox=Tabs.DPlayer:AddRightGroupbox('Reach')
PlayerBox:AddSlider("MovementSpeed",{Text="Movement Speed",Default=15,Min=15,Max=21,Rounding=1})
PlayerBox:AddToggle('EnableMovementSpeed',{Text="Enable Movement Speed",Default=false,Callback=function(v) if not v then localPlayer.Character.Humanoid.WalkSpeed=15 end end})
PlayerBox:AddDropdown("SpeedBypassMethod",{Values={"Method 1","Method 2"},Default=1,Text="Speed Bypass Method"})
PlayerBox:AddToggle('BypassSpeed',{Text="Speed Bypass",Default=false,Callback=function(v) Options.MovementSpeed:SetMax(v and 75 or 21) Options.FlightSpeed:SetMax(v and 75 or 21) end})
PlayerBox:AddDivider()
PlayerBox:AddToggle('NoAcc',{Text="Fast Stop",Default=false,Callback=function(v) if v then OldAccel=localPlayer.Character.HumanoidRootPart.CustomPhysicalProperties else if OldAccel then localPlayer.Character.HumanoidRootPart.CustomPhysicalProperties=OldAccel OldAccel=nil end end end})
PlayerBox:AddToggle('Flight',{Text="Flight",Default=false,Callback=function(v) if not v then if localPlayer.Character.HumanoidRootPart:FindFirstChild("FlightVelocity") then localPlayer.Character.HumanoidRootPart.FlightVelocity:Destroy() end end end}):AddKeyPicker("FlightKeybind",{Default="F",SyncToggleState=true,Mode="Toggle",Text="Flight",NoUI=false})
PlayerBox:AddSlider("FlightSpeed",{Text="Flight Speed",Default=15,Min=15,Max=75,Rounding=1})
PlayerBox:AddDivider()
PlayerBox:AddToggle('EnableJump',{Text="Enable Jumping",Default=false,Callback=function(v) if not v then localPlayer.Character:SetAttribute("CanJump",false) end end})
PlayerBox:AddToggle('InstaInteract',{Text="Instant Interact",Default=false,Callback=function(v) if v then for _,p in ipairs(workspace:GetDescendants()) do if p:IsA("ProximityPrompt") then p:SetAttribute("Duration",p.HoldDuration) p.HoldDuration=0 end end else for _,p in ipairs(workspace:GetDescendants()) do if p:IsA("ProximityPrompt") then p.HoldDuration=p:GetAttribute("Duration") or 0 end end end end})
PlayerBox:AddToggle('InfJump',{Text="Infinite Jump",Default=false})
PlayerBox:AddDivider()
PlayerBox:AddToggle('Godmode',{Text="God Mode",Default=false,Callback=function(v) if v and RemotesFolder.Name~="RemotesFolder" then localPlayer.Character.Collision.Position-=Vector3.new(0,4,0) end if v and RemotesFolder.Name=="RemotesFolder" then localPlayer.Character:PivotTo(localPlayer.Character.CollisionPart.CFrame*CFrame.new(0,-2,0)) end if not v and RemotesFolder.Name=="RemotesFolder" then localPlayer.Character.Humanoid.HipHeight=2.4 localPlayer.Character.Collision.Size=Vector3.new(5.5,3,3) localPlayer.Character.LowerTorso.Root.C1=CFrame.new(Vector3.new(0,0,0)) localPlayer.Character.Collision.CollisionCrouch.Size=Vector3.new(5.5,3,3) localPlayer.Character:PivotTo(localPlayer.Character.CollisionPart.CFrame*CFrame.new(0,2,0)) end if not v and RemotesFolder.Name~="RemotesFolder" then localPlayer.Character.Collision.Position=localPlayer.Character.HumanoidRootPart.Position end end}):AddKeyPicker("GodmodeKeybind",{Default="G",SyncToggleState=true,Mode="Toggle",Text="God Mode",NoUI=false})
AutoBox:AddToggle("AutoInteract",{Text="Auto Interact",Default=false,Callback=function(v) if v then for _,p in ipairs(workspace.CurrentRooms:GetDescendants()) do if p:IsA("ProximityPrompt") then if not (PromptIgnore[p.Name] or p.Parent.Name=="Padlock" or p.Parent:GetAttribute("JeffShop")) or p.Parent.Name=="RetroWardrobe" or p.Parent.Name=="KeyObtainFake" then table.insert(Interactions,p) end end end else table.clear(Interactions) end end}):AddKeyPicker("AutoInteractKeybind",{Default="R",SyncToggleState=true,Mode=Library.IsMobile and "Toggle" or "Hold",Text="Auto Interact",NoUI=false})
AutoBox:AddSlider("AutoInteractDelay",{Text="Auto Interact Delay",Default=0.05,Min=0,Max=0.2,Rounding=2})
AutoBox:AddSlider("AutoInteractreach",{Text="Auto Interact Range",Default=7,Min=7,Max=12,Rounding=2})
AutoBox:AddDivider()
AutoBox:AddToggle('AutoLibraryCode',{Text="Auto Library Code",Default=false})
AutoBox:AddToggle('BruteForceLibCode',{Text="Bruteforce Library Code",Default=false})
AutoBox:AddToggle('AutoHeartbeat',{Text="Auto Heartbeat Minigame",Default=false})
AutoBox:AddDivider()
AutoBox:AddToggle('AutoBreaker',{Text="Auto Breaker Box",Default=false,Callback=function(v) if v then for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="ElevatorBreaker" then Breaker(b) end end end end})
AutoBox:AddDropdown("AutoBreakerBoxMethod",{Values={"Legit","Exploit"},Default="Legit",Text="Auto Breaker Method",Callback=function(v) Method=v end})
ReachBox:AddToggle('PromptReach',{Text="Prompt Reach",Default=false,Callback=function(v) if v then for _,p in pairs(workspace:GetDescendants()) do if p:IsA("ProximityPrompt") then p:SetAttribute("Range",p.MaxActivationDistance) p.MaxActivationDistance=p.MaxActivationDistance*2 end end else for _,p in pairs(workspace:GetDescendants()) do if p:IsA("ProximityPrompt") then p.MaxActivationDistance=p:GetAttribute("Range") or p.MaxActivationDistance end end end end})
ReachBox:AddToggle('PromptClip',{Text="Prompt Clip",Default=false,Callback=function(v) if v then for _,p in pairs(workspace:GetDescendants()) do if p:IsA("ProximityPrompt") then p:SetAttribute("Clip",p.RequiresLineOfSight) p.RequiresLineOfSight=false end end else for _,p in pairs(workspace:GetDescendants()) do if p:IsA("ProximityPrompt") then p.RequiresLineOfSight=p:GetAttribute("Clip") or true end end end end})
if UserInputService.KeyboardEnabled then local d=false table.insert(Connections,UserInputService.JumpRequest:Connect(function() if Toggles.InfJump.Value and not d and localPlayer.Character then d=true localPlayer.Character.Humanoid:ChangeState(Enum.HumanoidStateType.Jumping,true) task.wait(0.1) d=false end end)) end

-- BYPASS TAB
local BypassEntityBox=Tabs.DBypass:AddLeftGroupbox('Bypass Entities') local BypassBox=Tabs.DBypass:AddRightGroupbox('Bypass')
local FakeScreech=Instance.new("RemoteEvent",RemotesFolder) FakeScreech.Name="Screech_"
local FakeA90=Instance.new("RemoteEvent",RemotesFolder) FakeA90.Name="A90_"
local gotS,gotA=false,false
BypassEntityBox:AddToggle('Screech',{Text="Anti Screech",Default=false,Callback=function(v) if v then gotS=true RemotesFolder.Screech.Name="Screech_" FakeScreech.Name="Screech" else if gotS then RemotesFolder["Screech_"].Name="Screech" FakeScreech.Name="Screech_" end end end})
BypassEntityBox:AddToggle('A90',{Text="Anti A90",Default=false,Callback=function(v) if v then gotA=true RemotesFolder.A90.Name="A90_" FakeA90.Name="A90" else if gotA then RemotesFolder["A90_"].Name="A90" FakeA90.Name="A90_" end end end})
BypassEntityBox:AddToggle('Dread',{Text="Anti Dread",Default=false,Callback=function(v) local D=localPlayer:FindFirstChild("Dread",true) or localPlayer:FindFirstChild("_Dread",true) if D then D.Name=v and "_Dread" or "Dread" end end})
BypassEntityBox:AddToggle('Halt',{Text="Anti Halt",Default=false,Callback=function(v) local D=ClientModules.EntityModules:FindFirstChild("Shade",true) or ClientModules.EntityModules:FindFirstChild("_Shade",true) if D then D.Name=v and "_Shade" or "Shade" end end})
BypassEntityBox:AddToggle('Jamming',{Text="Anti Jamming",Default=false,Callback=function(v) if ReplicatedStorage:FindFirstChild("LiveModifiers") and ReplicatedStorage.LiveModifiers:FindFirstChild("Jammin") then local Jam=localPlayer.PlayerGui.MainUI.Initiator:FindFirstChild("Main_Game").Health.Jam Jam.Playing=not v game:GetService("SoundService").Main.Jamming.Enabled=not v end end})
local Surge=Instance.new("RemoteEvent",ReplicatedStorage) Surge.Name="SurgeRemote"
BypassEntityBox:AddToggle('BypassSurgeDamage',{Text="Anti Surge",Default=false,Callback=function(v) if v then if RemotesFolder:FindFirstChild("SurgeRemote") then RemotesFolder.SurgeRemote.Parent=ReplicatedStorage Surge.Parent=RemotesFolder end else if RemotesFolder:FindFirstChild("SurgeRemote") then ReplicatedStorage.SurgeRemote.Parent=RemotesFolder Surge.Parent=ReplicatedStorage end end end})
BypassEntityBox:AddToggle('Snare',{Text="Anti Snare",Default=false,Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="Snare" then local w=0 repeat task.wait(0.01) w=w+0.01 until w>2 or b:FindFirstChild("Hitbox") if b:FindFirstChild("Hitbox") then b.Hitbox.CanTouch=not v end end end end})
BypassEntityBox:AddToggle('Giggle',{Text="Anti Giggle",Default=false,Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="GiggleCeiling" then local w=0 repeat task.wait(0.01) w=w+0.01 until w>2 or b:FindFirstChild("Hitbox") if b:FindFirstChild("Hitbox") then b.Hitbox.CanTouch=not v end end end end})
BypassEntityBox:AddToggle('Dupe',{Text="Anti Dupe",Default=false,Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="DoorFake" and b.Parent.Name=="SideroomDupe" then b:WaitForChild("Hidden",9e9).CanTouch=not v end end end})
BypassEntityBox:AddToggle('EyesDamage',{Text="Anti Eyes",Default=false})
BypassEntityBox:AddToggle('LookmanDamage',{Text="Anti Lookman",Default=false})
BypassEntityBox:AddToggle('GloomEggDamage',{Text="Anti Gloom Egg",Default=false,Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="GloomEgg" then for _,i in pairs(b:GetChildren()) do if i:IsA("BasePart") then i.CanTouch=not v end end end end end})
BypassEntityBox:AddToggle('FigureHearing',{Text="Anti Figure Hearing",Default=false,Callback=function(v) RemotesFolder.Crouch:FireServer(v and true or false) end})
BypassBox:AddToggle('AntiCheatMani',{Text="Slowclip",Default=false,Callback=function(v) if not v then if localPlayer.Character.HumanoidRootPart:FindFirstChild("VelocityMani") then localPlayer.Character.HumanoidRootPart.VelocityMani:Destroy() end if Toggles.NoClip and Toggles.NoClip.Value then Toggles.NoClip:SetValue(false) end end end}):AddKeyPicker("AntiCheatMan",{Default="V",SyncToggleState=true,Mode=Library.IsMobile and "Toggle" or "Hold",Text="Slowclip",NoUI=false})
BypassBox:AddDropdown("AntiCheatManiMethod",{Values={"Velocity","Anticheat"},Default=1,Text="Slowclip Method"})
BypassBox:AddDivider()
BypassBox:AddToggle('InfItems',{Text="Infinite Items",Default=false,Callback=function(v) if v then for _,p in pairs(workspace.CurrentRooms:GetDescendants()) do if p:IsA("ProximityPrompt") then if Names[p.Parent.Name] or p.Name=="FusesPrompt" or p.Parent.Parent.Name=="Locker_Small_Locked" then table.insert(Stored,p) end end end else table.clear(Stored) end end})

-- VISUALS TAB
local CameraBox=Tabs.DVisuals:AddLeftGroupbox('Camera') local LightingBox=Tabs.DVisuals:AddLeftGroupbox('Lighting') local ESPBox=Tabs.DVisuals:AddRightGroupbox('ESP') local ESPSettings=Tabs.DVisuals:AddRightGroupbox('ESP Settings') local NotifyBox=Tabs.DVisuals:AddLeftGroupbox('Notifying')
CameraBox:AddSlider("FOV",{Text="FOV",Default=70,Min=70,Max=120,Rounding=1})
CameraBox:AddToggle('NoCamShake',{Text="No Camera Shake",Disabled=not Require})
CameraBox:AddToggle('Freecam',{Text="Freecam",Default=false,Callback=function(v) if not v then local fc=workspace:FindFirstChild("FreecamPart") if fc then fc:Destroy() local root=localPlayer.Character and localPlayer.Character:FindFirstChild("HumanoidRootPart") if root then root.Anchored=false end localPlayer.CameraMinZoomDistance=localPlayer:GetAttribute("fc_om") or 0.5 localPlayer.CameraMaxZoomDistance=localPlayer:GetAttribute("fc_ox") or 128 end end end}):AddKeyPicker("FreecamKeybind",{Default="B",SyncToggleState=true,Mode="Toggle",Text="Freecam",NoUI=false})
CameraBox:AddToggle('NoScenes',{Text="No Cutscenes",Default=false,Callback=function(v) local C=RemoteListener:FindFirstChild("Cutscenes") or RemoteListener:FindFirstChild("Cutscenes_") C.Name=v and "Cutscenes_" or "Cutscenes" end})
LightingBox:AddToggle('NoFog',{Text="No Fog",Default=false,Callback=function(v) if not v then for _,a in pairs(Lighting:GetChildren()) do if a:IsA("Atmosphere") then a.Density=0.94 end end end if v then OldFogEnd=Lighting.FogEnd else if OldFogEnd then Lighting.FogEnd=OldFogEnd OldFogEnd=nil end end end})
LightingBox:AddToggle('FullBright',{Text="Fullbright",Default=false,Callback=function(v) if not v then Lighting.Ambient=Color3.fromRGB(0,0,0) Lighting.GlobalShadows=true end end})
ESPSettings:AddToggle('ShowDistance',{Text="Show ESP Distance",Default=true,Callback=function(v) ESPLibrary:SetShowDistance(v) end})
ESPSettings:AddToggle('ShowTracers',{Text="Show ESP Tracers",Default=true,Callback=function(v) ESPLibrary:SetTracers(v) end})
ESPSettings:AddToggle('ShowRainbow',{Text="Show ESP Rainbow",Default=false,Callback=function(v) ESPLibrary:SetRainbow(v) end})
ESPSettings:AddDropdown("SetESPMode",{Text="Set ESP Mode",Values={"Highlight/Text","Text","Highlight"},Default=1,Callback=function(v) ESPLibrary:SetESPMode(v) end})
ESPSettings:AddDropdown("SetFont",{Text="Set Font",Values={"Legacy","Arial","ArialBold","SourceSans","SourceSansBold","Gotham","GothamBold","Code","Highway","SciFi","Arcade","Fantasy","Cartoon","Roboto","RobotoMono","Oswald","Ubuntu"},Default=8,Callback=function(v) ESPLibrary:SetFont(v) end})
ESPBox:AddToggle('Door',{Text="Door",Default=false,Callback=function(v) if v then local Doo=workspace.CurrentRooms[localPlayer:GetAttribute("CurrentRoom")+1].Door.Door AddESP(Doo,"Door "..Doo.Parent:GetAttribute("RoomID"),DoorColor) AddESP(workspace.CurrentRooms[localPlayer:GetAttribute("CurrentRoom")].Door.Door,"Door",DoorColor) else for _,r in ipairs(workspace.CurrentRooms:GetChildren()) do ESPLibrary:RemoveESP(r.Door.Door) end end end}):AddColorPicker("DoorClr",{Default=DoorColor,Title="Door Color",Callback=function(v) DoorColor=v Toggles.Door:SetValue(false) Toggles.Door:SetValue(true) end})
ESPBox:AddToggle('Objective',{Text="Objective",Default=false,Callback=function(v) if v then for _,o in pairs(workspace.CurrentRooms:GetDescendants()) do local b=Items[o.Name] if b then AddESP(o,b,ItemsColor) end if o.Name=="KeyObtain" then repeat task.wait() until o.PrimaryPart AddESP(o,"Key",ItemsColor) end end else for _,o in pairs(workspace.CurrentRooms:GetDescendants()) do if Items[o.Name] or o.Name=="KeyObtain" then ESPLibrary:RemoveESP(o) end end end end}):AddColorPicker("ObjClr",{Default=ItemsColor,Title="Objective Color",Callback=function(v) ItemsColor=v if Toggles.Objective.Value then Toggles.Objective:SetValue(false) Toggles.Objective:SetValue(true) end end})
ESPBox:AddToggle('HidingPlace',{Text="Hiding Place",Default=false,Callback=function(v) for _,c in pairs(Closets) do local n=HidingPlaces[c.Name] if n then if v and c:IsDescendantOf(workspace.CurrentRooms[localPlayer:GetAttribute("CurrentRoom")]) then AddESP(c,n,HidingPlaceColor) else ESPLibrary:RemoveESP(c) end end end end}):AddColorPicker("HideClr",{Default=HidingPlaceColor,Title="Hiding Place Color",Callback=function(v) HidingPlaceColor=v end})
ESPBox:AddToggle('GateLever',{Text="Gate Lever",Default=false,Callback=function(v) local L=workspace.CurrentRooms[localPlayer:GetAttribute("CurrentRoom")]:FindFirstChild("LeverForGate",true) if v and L then AddESP(L,"Gate Lever",LeverColor) elseif L then ESPLibrary:RemoveESP(L) end end}):AddColorPicker("LeverClr",{Default=LeverColor,Title="Lever Color",Callback=function(v) LeverColor=v end})
ESPBox:AddToggle('Books',{Text="Library Book",Default=false,Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="LiveHintBook" then if v then AddESP(b,"Library Book",BookColor) else ESPLibrary:RemoveESP(b) end end end end}):AddColorPicker("BookClr",{Default=BookColor,Title="Book Color",Callback=function(v) BookColor=v end})
ESPBox:AddToggle('Breakers',{Text="Breaker",Default=false,Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="LiveBreakerPolePickup" then if v then AddESP(b,"Breaker",BreakerColor) else ESPLibrary:RemoveESP(b) end end end end}):AddColorPicker("BrkClr",{Default=BreakerColor,Title="Breaker Color",Callback=function(v) BreakerColor=v end})
ESPBox:AddToggle('Gold',{Text="Gold",Default=false,Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="GoldPile" then if v then AddESP(b,"Gold "..b:GetAttribute("GoldValue"),GoldColor) else ESPLibrary:RemoveESP(b) end end end end}):AddColorPicker("GoldClr",{Default=GoldColor,Title="Gold Color",Callback=function(v) GoldColor=v end})
ESPBox:AddToggle('Ladder',{Text="Ladder",Default=false,Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="Ladder" then if v then AddESP(b,"Ladder",LadderColor) else ESPLibrary:RemoveESP(b) end end end end}):AddColorPicker("LadClr",{Default=LadderColor,Title="Ladder Color",Callback=function(v) LadderColor=v end})
ESPBox:AddToggle('Fuse',{Text="Fuse",Default=false,Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="FuseObtain" then if v then AddESP(b,"Fuse",FuseColor) else ESPLibrary:RemoveESP(b) end end end end}):AddColorPicker("FuseClr",{Default=FuseColor,Title="Fuse Color",Callback=function(v) FuseColor=v end})
ESPBox:AddToggle('Entity',{Text="Entity",Default=false,Callback=function(v) task.spawn(function() if v then for _,e in pairs(workspace.CurrentRooms:GetDescendants()) do local lab=roomEntities[e.Name] if lab then AddEntityESP(e,lab,EntityColor) end end for _,e in pairs(workspace:GetChildren()) do local lab=workspaceEntities[e.Name] if lab then AddEntityESP(e,lab,EntityColor) end end else for _,e in pairs(workspace.CurrentRooms:GetDescendants()) do if roomEntities[e.Name] then ESPLibrary:RemoveESP(e) end end for _,e in pairs(workspace:GetChildren()) do if workspaceEntities[e.Name] then ESPLibrary:RemoveESP(e) end end end end) end}):AddColorPicker("EntClr",{Default=EntityColor,Title="Entity Color",Callback=function(v) EntityColor=v if Toggles.Entity.Value then Toggles.Entity:SetValue(false) Toggles.Entity:SetValue(true) end end})
ESPBox:AddToggle('Player',{Text="Player",Default=false,Callback=function(v) for _,p in pairs(Players:GetPlayers()) do if p~=localPlayer and p.Character then ESPLibrary:RemoveESP(p.Character) if v then local h=p.Character:FindFirstChildOfClass("Humanoid") if h and h.Health>0 then AddESP(p.Character,p.Name.." ["..math.floor((h.Health/h.MaxHealth)*100).."%]",PlayerColor) end end end end end}):AddColorPicker("PlrClr",{Default=PlayerColor,Title="Player Color",Callback=function(v) PlayerColor=v Toggles.Player:SetValue(false) Toggles.Player:SetValue(true) end})
NotifyBox:AddDropdown("Notify",{Values={"Rush","Ambush","GlitchRush","GlitchAmbush","A-60","A-120","Eyes","Blitz","Lookman","Jeff"},Default=1,Multi=true,Text="Choose to Notify"})
NotifyBox:AddToggle('NotifySpawn',{Text="Notify Entity",Default=false})

-- FLOOR TAB
local HotelFloor=Tabs.DFloor:AddLeftGroupbox('Hotel') local MinesFloor=Tabs.DFloor:AddRightGroupbox('Mines') local FoolsFloor=Tabs.DFloor:AddRightGroupbox('Fools') local RoomsFloor=Tabs.DFloor:AddLeftGroupbox('Rooms') local RetroFloor=Tabs.DFloor:AddLeftGroupbox('Retro') local GameBox=Tabs.DFloor:AddRightGroupbox('Game Management')
GameBox:AddButton({Text="Revive",DoubleClick=true,Func=function() RemotesFolder.Revive:FireServer() end})
GameBox:AddButton({Text="Play Again",DoubleClick=true,Func=function() RemotesFolder.PlayAgain:FireServer() end})
local Pressed=false
GameBox:AddButton({Text="Reset",DoubleClick=true,Func=function() Pressed=not Pressed if not Pressed then if RemotesFolder:FindFirstChild("Underwater") then RemotesFolder.Underwater:FireServer(false) end return end if ReplicateSignal then replicatesignal(localPlayer.Kill) else Notify("Reset","Double Click to stop") task.spawn(function() while Pressed and localPlayer:GetAttribute("Alive")~=false do if RemotesFolder:FindFirstChild("Underwater") then RemotesFolder.Underwater:FireServer(true) end task.wait() end if RemotesFolder:FindFirstChild("Underwater") then RemotesFolder.Underwater:FireServer(false) end Pressed=false end) end end})
GameBox:AddButton({Text="Lobby",DoubleClick=true,Func=function() RemotesFolder.Lobby:FireServer() end})
RetroFloor:AddToggle('AntiLava',{Text="Anti Lava",Default=false,Disabled=CurrentFloor~="Retro",Callback=function(v) for _,l in pairs(workspace.CurrentRooms:GetDescendants()) do if l.Name=="Lava" then l.CanTouch=not v end end end})
RetroFloor:AddToggle('AntiWall',{Text="Anti Seek Wall",Default=false,Disabled=CurrentFloor~="Retro",Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="ScaryWall" then for _,i in pairs(b:GetChildren()) do if i:IsA("BasePart") then i.CanTouch=not v end end end end end})
RetroFloor:AddToggle('RealBridge',{Text="Show Real Bridge",Default=false,Disabled=CurrentFloor~="Retro",Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="Bridge" and b.CanCollide==false then b.Transparency=v and 1 or 0 end end end})
FoolsFloor:AddToggle('AntiBanana',{Text="Anti Banana",Default=false,Disabled=CurrentFloor~="Fools",Callback=function(v) for _,b in pairs(workspace:GetChildren()) do if b.Name=="BananaPeel" then b.CanTouch=not v end end end})
FoolsFloor:AddToggle('AntiJeff',{Text="Anti Jeff",Default=false,Disabled=CurrentFloor~="Fools",Callback=function(v) local b=workspace:FindFirstChild("JeffTheKiller") if b and b.Name=="JeffTheKiller" then repeat task.wait() until b.PrimaryPart and IsNetworkOwner and isnetworkowner(b.PrimaryPart) for _,i in pairs(b:GetChildren()) do if i:IsA("BasePart") then i.CanTouch=not v end end b.Humanoid.Health=v and 0 or 100 end end})
FoolsFloor:AddToggle('InfRevive',{Text="Infinite Revive",Default=false,Disabled=CurrentFloor~="Fools" and not isBricks})
FoolsFloor:AddToggle('DeleteSeekFE',{Text="Delete Seek (FE)",Default=false,Disabled=CurrentFloor~="Fools" and not isBricks,Callback=function(v) if v then for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="TriggerEventCollision" then Notify("Doors","Deleting Seek...") for _,i in pairs(b:GetChildren()) do if i.Name=="Collision" and FireTouch then firetouchinterest(localPlayer.Character.HumanoidRootPart,i,0) end end task.wait(0.5) Notify("Doors",b:FindFirstChild("Collision") and "Failed" or "Deleted Seek!") end end end end})
local Control if Require then Control=require(localPlayer.PlayerScripts.PlayerModule):GetControls().GetMoveVector end
MinesFloor:AddToggle('DeleteFigureFE',{Text="Delete Figure (FE)",Default=false,Disabled=CurrentFloor~="Mines" and not isBricks,Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="FigureRig" or b.Name=="FigureRagdoll" then table.insert(Figures,b) end end end})
MinesFloor:AddToggle('ShowPath',{Text="Show Seek Path",Default=false,Disabled=CurrentFloor~="Mines",Callback=function(v) if v then for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="SeekGuidingLight" then ShowSeekPath(b) end end else SeekPath:ClearAllChildren() end end})
MinesFloor:AddToggle('FixBrokenBridge',{Text="Fix Broken Bridge",Default=false,Disabled=CurrentFloor~="Mines",Callback=function(v) if v then for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="Bridge" then FixBridge(b) end end else for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="BridgeBarrier" then b:Destroy() end end end end})
MinesFloor:AddToggle('AutoMinecart',{Text="Auto Minecart",Default=false,Disabled=CurrentFloor~="Mines",Callback=function(v) if v then for _,b in workspace.CurrentRooms:GetDescendants() do if b.Name=="DuckBoard" then table.insert(DuckBoards,b) end if string.find(b.Name,"MinecartNode") then table.insert(Nodes,b) end end else if Require then require(localPlayer.PlayerScripts.PlayerModule):GetControls().GetMoveVector=Control end table.clear(Nodes) table.clear(DuckBoards) end end})
MinesFloor:AddToggle('AutoAnchorSolver',{Text="Auto Anchor Solver",Default=false,Disabled=CurrentFloor~="Mines",Callback=function(v) if v then for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="MinesAnchor" then table.insert(Anchors,b) end end end end})
MinesFloor:AddToggle('AntiSeekFlood',{Text="Anti Seek Flood",Default=false,Disabled=CurrentFloor~="Mines",Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="SeekFloodline" then b.CanCollide=v end end end})
RoomsFloor:AddToggle('AutoRooms',{Text="Auto A-1000",Default=false,Disabled=CurrentFloor~="Rooms",Callback=function(v) if not v then PathFolder:ClearAllChildren() if localPlayer.Character then localPlayer.Character.Collision.Size=Vector3.new(5.5,3,3) localPlayer.Character.Humanoid:MoveTo(localPlayer.Character.HumanoidRootPart.Position) end end end})
RoomsFloor:AddToggle('IgnoreA60',{Text="Ignore A-60",Default=false,Disabled=CurrentFloor~="Rooms"})
HotelFloor:AddToggle('NotifyLibraryCode',{Text="Notify Library Code",Default=false,Disabled=CurrentFloor~="Hotel" and not isBricks and CurrentFloor~="Fools"})
HotelFloor:AddToggle('SeekObf',{Text="Anti Seek Obstacles",Default=false,Disabled=CurrentFloor=="Retro",Callback=function(v) for _,b in pairs(workspace.CurrentRooms:GetDescendants()) do if b.Name=="Seek_Arm" or b.Name=="ChandelierObstruction" then for _,i in pairs(b:GetChildren()) do if i:IsA("BasePart") then i.CanTouch=not v end end end end end})

-- bypass loops + engine
task.spawn(function() while task.wait(Options.SpeedBypassMethod.Value=="Method 1" and 0 or 0.209) do if Library.Unloaded then break end if Options.SpeedBypassMethod.Value=="Method 1" then if Toggles.BypassSpeed.Value then if CollisionClone then CollisionClone.Massless=true end RemotesFolder.Crouch:FireServer(true,true) end elseif Options.SpeedBypassMethod.Value=="Method 2" then local char=localPlayer.Character local hrp=char and char:FindFirstChild("HumanoidRootPart") if localPlayer:GetAttribute("Alive") and hrp and CollisionClone and CollisionClone.Parent then Params.FilterDescendantsInstances={char,CollisionClone} if not workspace:Raycast(hrp.Position,Vector3.new(0,-100,0),Params) or not Toggles.BypassSpeed.Value then CollisionClone.Massless=true else if localPlayer:GetAttribute("Alive") then CollisionClone.Massless=true end task.wait(0.209) if localPlayer:GetAttribute("Alive") and CollisionClone and CollisionClone.Parent then CollisionClone.Massless=false end end end end end end)
if HookMeta then local Old Old=hookmetamethod(game,"__namecall",function(Self,...) if Library.Unloaded then return Old(Self,...) end local Mm=getnamecallmethod() if Mm=="FireServer" or Mm=="InvokeServer" then if Toggles.AutoHeartbeat.Value and Self.Name=="ClutchHeartbeat" then return Old(Self,true) end if Mm=="FireServer" and Toggles.FigureHearing.Value and Self.Name=="Crouch" then return Old(Self,true,true) end end return Old(Self,...) end) end
local getcons=getconnections or get_signal_cons or get_relative_connections
if getcons then for _,c in pairs(getcons(localPlayer.Idled)) do if c.Disable then c:Disable() end end end

local AI,NC,AAS,IID,PE=0,0,0,0,0
table.insert(Connections,RunService.RenderStepped:Connect(function(dt)
    AI+=dt NC+=dt AAS+=dt IID+=dt PE+=dt
    if not localPlayer:GetAttribute("Alive") then if Toggles.InfRevive.Value then RemotesFolder.Revive:FireServer() end if CollisionClone then CollisionClone=nil end return end
    if camera~=workspace.CurrentCamera then camera=workspace.CurrentCamera end
    if not localPlayer.Character:GetAttribute("Climbing") and Toggles.EnableMovementSpeed.Value then if localPlayer.Character.Humanoid.WalkSpeed~=Options.MovementSpeed.Value then localPlayer.Character.Humanoid.WalkSpeed=Options.MovementSpeed.Value end end
    camera.FieldOfView=Options.FOV.Value
    if Toggles.Freecam.Value then local char=localPlayer.Character local hum=char and char:FindFirstChild("Humanoid") local root=char and char:FindFirstChild("HumanoidRootPart") if root and not root.Anchored then root.Anchored=true end if not workspace:FindFirstChild("FreecamPart") then local part=Instance.new("Part") part.Name="FreecamPart" part.Size=Vector3.new(0.01,0.01,0.01) part.Transparency=1 part.CanCollide=false part.Anchored=true part.CFrame=camera.CFrame part.Parent=workspace localPlayer:SetAttribute("fc_om",localPlayer.CameraMinZoomDistance) localPlayer:SetAttribute("fc_ox",localPlayer.CameraMaxZoomDistance) localPlayer.CameraMinZoomDistance=0 localPlayer.CameraMaxZoomDistance=0 local rx,ry=camera.CFrame:ToOrientation() localPlayer:SetAttribute("fc_p",math.deg(rx)) localPlayer:SetAttribute("fc_y",math.deg(ry)) end local fc=workspace:FindFirstChild("FreecamPart") if fc then local d=UserInputService:GetMouseDelta() local sens=UserInputService.KeyboardEnabled and 0.3 or 0.6 local pitch=math.clamp((localPlayer:GetAttribute("fc_p") or 0)-(d.Y*sens),-80,80) local yaw=(localPlayer:GetAttribute("fc_y") or 0)-(d.X*sens) localPlayer:SetAttribute("fc_p",pitch) localPlayer:SetAttribute("fc_y",yaw) fc.CFrame=CFrame.new(fc.Position)*CFrame.fromOrientation(math.rad(pitch),math.rad(yaw),0) camera.CFrame=fc.CFrame camera.Focus=camera.CFrame*CFrame.new(0,0,-10) if hum and hum.MoveDirection.Magnitude>0 then local mv=hum.MoveDirection local lm=camera.CFrame:VectorToObjectSpace(mv) local fm=(camera.CFrame.RightVector*lm.X)+(camera.CFrame.LookVector*-lm.Z) fc.Position=fc.Position+(fm*75*dt) end end end
    if Toggles.DeleteFigureFE.Value and Figures then for _,v in pairs(Figures) do local Root=v:FindFirstChild("Root") if not IsNetworkOwner then Toggles.DeleteFigureFE:SetValue(false) elseif Root and isnetworkowner(Root) then if Root:FindFirstChild("BodyForce") then Root.BodyForce.Force=Vector3.new(0,-50000,0) else Root:PivotTo(CFrame.new(0,-50000,0)) end for _,part in pairs(v:GetDescendants()) do if part:IsA("BasePart") and part.CanCollide then part.CanCollide=false part.Anchored=false end end end end end
    if Toggles.AutoAnchorSolver.Value and LatestRoom.Value==50 and AAS>0.5 then AAS=0 local Hint=localPlayer.PlayerGui.MainUI:FindFirstChild("AnchorHintFrame") if Anchors and Hint and Hint.Visible then local ID=Hint.AnchorCode.Text for _,v in pairs(Anchors) do if v:FindFirstChild("Sign") and v.Sign.TextLabel.Text==ID then local Code=Hint.Code.Text if (localPlayer.Character.HumanoidRootPart.Position-v:GetPivot().Position).Magnitude<20 then local AR=v:FindFirstChildOfClass("RemoteFunction") if AR then AR:InvokeServer(tostring(Code)) end end end end end end
    if Toggles.InfItems.Value and IID>0.15 then IID=0 for _,p in pairs(Stored) do InfPrompt(p) end end
    if Toggles.NotifyLibraryCode.Value and NC>5 then NC=0 local Code=GetLibraryCode() if Code and LatestRoom.Value==50 then Notify("Doors","Code "..Code) end end
    if Toggles.AutoLibraryCode.Value and LatestRoom.Value==50 then local Code=GetLibraryCode() if Code then if Toggles.BruteForceLibCode.Value and string.find(Code,"_") then local B="" for i=1,#Code do local c=string.sub(Code,i,i) B=B..(c=="_" and tostring(math.random(0,9)) or c) end Code=B end PL:FireServer(Code) end end
    if Toggles.Flight.Value then if not localPlayer.Character.HumanoidRootPart:FindFirstChild("FlightVelocity") then local V=Instance.new("BodyVelocity",localPlayer.Character.HumanoidRootPart) V.MaxForce=Vector3.new(math.huge,math.huge,math.huge) V.Velocity=Vector3.zero V.Name="FlightVelocity" V.P=math.huge end local md=localPlayer.Character.Humanoid.MoveDirection local fl=camera.CFrame.LookVector*Vector3.new(1,0,1) if fl.Magnitude<0.001 then fl=camera.CFrame.UpVector*Vector3.new(1,0,1)*math.sign(-camera.CFrame.LookVector.Y) end local fc2=CFrame.lookAt(Vector3.zero,fl) local li=fc2:VectorToObjectSpace(md) localPlayer.Character.HumanoidRootPart.FlightVelocity.Velocity=camera.CFrame:VectorToWorldSpace(li)*Options.FlightSpeed.Value end
    if Toggles.Godmode.Value and RemotesFolder.Name=="RemotesFolder" then if not Toggles.FigureHearing.Value then Toggles.FigureHearing:SetValue(true) end if localPlayer.Character.LowerTorso.Root.C1~=CFrame.new(0,-2.3,0) then localPlayer.Character.LowerTorso.Root.C1=CFrame.new(0,-2.3,0) end if localPlayer.Character.Humanoid.HipHeight~=0.22 then localPlayer.Character.Humanoid.HipHeight=0.22 end if localPlayer.Character.Collision.Size~=Vector3.new(1,1,4) then localPlayer.Character.Collision.Size=Vector3.new(1,1,4) end if localPlayer.Character.Collision.CollisionCrouch.Size~=Vector3.new(1,1,4) then localPlayer.Character.Collision.CollisionCrouch.Size=Vector3.new(1,1,4) end end
    if not localPlayer.Character:FindFirstChild("CollisionClone") then if localPlayer.Character:FindFirstChild("CollisionPart") then CollisionClone=localPlayer.Character.CollisionPart:Clone() CollisionClone.Parent=localPlayer.Character CollisionClone.Name="CollisionClone" CollisionClone.RootPriority=127 CollisionClone.Anchored=false CollisionClone.CanCollide=false if CollisionClone:FindFirstChild("CollisionCrouch") then CollisionClone.CollisionCrouch:Destroy() end end end
    if Toggles.NoAcc.Value and not Toggles.Flight.Value then if localPlayer.Character.HumanoidRootPart.CustomPhysicalProperties~=PhysicalProperties.new(100,0.1,0.1,0.1,0.1) then localPlayer.Character.HumanoidRootPart.CustomPhysicalProperties=PhysicalProperties.new(100,0.1,0.1,0.1,0.1) end end
    if Toggles.EnableJump.Value and not localPlayer.Character:GetAttribute("CanJump") then localPlayer.Character:SetAttribute("CanJump",true) end
    if Toggles.AutoInteract.Value and AI>Options.AutoInteractDelay.Value then AI=0 if localPlayer.Character and localPlayer.Character:FindFirstChild("HumanoidRootPart") then for _,prompt in Interactions do if not prompt.Parent then continue end if (prompt.Parent.Name=="GoldPile" and CurrentFloor=="Fools") or prompt.Parent.Name=="KeyObtainFake" or prompt.Parent.Name=="Mandrake" then continue end if prompt:GetAttribute("InfItems") and prompt.Name~="InfPrompt" then continue end if prompt.Parent:IsA("BasePart") or prompt.Parent:IsA("Model") then local TP=prompt.Parent:IsA("BasePart") and prompt.Parent or (prompt.Parent.PrimaryPart or prompt.Parent:FindFirstChildWhichIsA("BasePart")) if TP and (localPlayer.Character.HumanoidRootPart.Position-TP.Position).Magnitude<=Options.AutoInteractreach.Value then if not prompt.Enabled then prompt.Enabled=true end if Firepp then fireproximityprompt(prompt) else prompt:InputHoldBegin() prompt:InputHoldEnd(prompt.HoldDuration or 0) end end end end end end
    if Toggles.NoFog.Value then if Lighting.FogEnd<100000 then Lighting.FogEnd=100000 end for _,a in pairs(Lighting:GetChildren()) do if a:IsA("Atmosphere") and a.Density>0 then a.Density=0 end end end
    if Toggles.NoCamShake.Value and RequiredMainGame then RequiredMainGame.csgo=CFrame.new(0,0,0) end
    if Toggles.Player.Value and PE>1 then PE=0 for _,v in pairs(Players:GetPlayers()) do if v~=localPlayer and v.Character then local h=v.Character:FindFirstChildOfClass("Humanoid") if h then if h.Health>0 then AddESP(v.Character,v.Name.." ["..math.floor((h.Health/h.MaxHealth)*100).."%]",PlayerColor) else ESPLibrary:RemoveESP(v.Character) end end end end end
    if Toggles.EyesDamage.Value then if (workspace:FindFirstChild("Eyes") or workspace:FindFirstChild("Lookman")) and not localPlayer.Character:GetAttribute("Hiding") then if RemotesFolder.Name~="RemotesFolder" then MotorReplication:FireServer(0,-650,0,false) else MotorReplication:FireServer(-650) end end end
    if Toggles.LookmanDamage.Value then if workspace:FindFirstChild("BackdoorLookman") and not localPlayer.Character:GetAttribute("Hiding") then MotorReplication:FireServer(-650) end end
    if Toggles.FullBright.Value then if Lighting.Ambient~=Color3.new(1,1,1) then Lighting.Ambient=Color3.new(1,1,1) end local cr=workspace.CurrentRooms:FindFirstChild(tostring(localPlayer:GetAttribute("CurrentRoom"))) if cr then if not cr:GetAttribute("OldAmbient") then cr:SetAttribute("OldAmbient",cr:GetAttribute("Ambient")) end if cr:GetAttribute("Ambient")~=Color3.new(1,1,1) then cr:SetAttribute("Ambient",Color3.new(1,1,1)) end end end
    if Toggles.AntiCheatMani.Value and localPlayer.Character and localPlayer.Character:FindFirstChild("HumanoidRootPart") then if Options.AntiCheatManiMethod.Value=="Velocity" then local BV=localPlayer.Character.HumanoidRootPart:FindFirstChild("VelocityMani") or Instance.new("BodyVelocity",localPlayer.Character.HumanoidRootPart) local lv=localPlayer.Character.HumanoidRootPart.CFrame.LookVector*2 BV.Velocity=Vector3.new(lv.X,lv.Y,lv.Z) BV.MaxForce=Vector3.new(math.huge,math.huge,math.huge) BV.Name="VelocityMani" else localPlayer.Character:PivotTo(localPlayer.Character:GetPivot()*CFrame.new(0,0,10000)) end end
    if Options.AutoInteractKeybind:GetState() and not Toggles.AutoInteract.Value then Toggles.AutoInteract:SetValue(true) end
    if not Options.AutoInteractKeybind:GetState() and Toggles.AutoInteract.Value then Toggles.AutoInteract:SetValue(false) end
    if Options.AntiCheatMan:GetState() and not Toggles.AntiCheatMani.Value then Toggles.AntiCheatMani:SetValue(true) end
    if not Options.AntiCheatMan:GetState() and Toggles.AntiCheatMani.Value then Toggles.AntiCheatMani:SetValue(false) end
end))

table.insert(Connections,workspace.ChildAdded:Connect(function(v) if Toggles.AntiBanana and Toggles.AntiBanana.Value and v.Name=="BananaPeel" then v.CanTouch=false end if Toggles.NotifySpawn.Value then local m=workspaceEntities[v.Name] if m and Options.Notify.Value[m=="A-60" and "A-60" or m] then Notify("Doors",m.." has Spawned") end end if Toggles.Entity.Value then local lab=workspaceEntities[v.Name] if lab then AddEntityESP(v,lab,EntityColor) end end end))
table.insert(Connections,workspace.DescendantAdded:Connect(function(v) local t=0 repeat task.wait(0.03) t+=0.03 until v.Parent or t>0.5 if not v.Parent then return end if v.Parent:FindFirstChildOfClass("Humanoid") then return end if HidingPlaces[v.Name] then table.insert(Closets,v) end if Toggles.Ladder.Value and v.Name=="Ladder" then AddESP(v,"Ladder",LadderColor) end if Toggles.Fuse.Value and v.Name=="FuseObtain" then AddESP(v,"Fuse",FuseColor) end if Toggles.Gold.Value and v.Name=="GoldPile" then AddESP(v,"Gold "..v:GetAttribute("GoldValue"),GoldColor) end if Toggles.Books.Value and v.Name=="LiveHintBook" then AddESP(v,"Library Book",BookColor) end if Toggles.Breakers.Value and v.Name=="LiveBreakerPolePickup" then AddESP(v,"Breaker",BreakerColor) end if Toggles.Objective.Value then local b=Items[v.Name] if b then AddESP(v,b,ItemsColor) end end if Toggles.AutoBreaker.Value and v.Name=="ElevatorBreaker" then Breaker(v) end if Toggles.InstaInteract.Value and v:IsA("ProximityPrompt") then v:SetAttribute("Duration",v.HoldDuration) v.HoldDuration=0 end if Toggles.PromptReach.Value and v:IsA("ProximityPrompt") then v:SetAttribute("Range",v.MaxActivationDistance) v.MaxActivationDistance=v.MaxActivationDistance*2 end if Toggles.PromptClip.Value and v:IsA("ProximityPrompt") then v:SetAttribute("Clip",v.RequiresLineOfSight) v.RequiresLineOfSight=false end if Toggles.InfItems.Value and v:IsA("ProximityPrompt") then if Names[v.Parent.Name] or v.Name=="FusesPrompt" or v.Parent.Parent.Name=="Locker_Small_Locked" then table.insert(Stored,v) end end if Toggles.AutoInteract.Value and v:IsA("ProximityPrompt") then if not (PromptIgnore[v.Name] or v.Parent.Name=="Padlock" or v.Parent:GetAttribute("JeffShop")) then table.insert(Interactions,v) end end if Toggles.Entity.Value and roomEntities[v.Name] then AddEntityESP(v,roomEntities[v.Name],EntityColor) end if Toggles.DeleteFigureFE.Value and (v.Name=="FigureRig" or v.Name=="FigureRagdoll") then table.insert(Figures,v) end if Toggles.AutoMinecart.Value then if v.Name=="DuckBoard" then table.insert(DuckBoards,v) end if string.find(v.Name,"MinecartNode") then table.insert(Nodes,v) end end if Toggles.AutoAnchorSolver.Value and v.Name=="MinesAnchor" then table.insert(Anchors,v) end end))
table.insert(Connections,workspace.DescendantRemoving:Connect(function(v) for i,g in pairs(Interactions) do if g==v then table.remove(Interactions,i) break end end for i,g in pairs(Closets) do if v==g then table.remove(Closets,i) end end for i,k in pairs(Stored) do
if v==k then table.remove(Stored,i) end end end))

table.insert(Connections,localPlayer:GetAttributeChangedSignal("CurrentRoom"):Connect(function() local cr=localPlayer:GetAttribute("CurrentRoom") if Toggles.Door.Value then local OD=workspace.CurrentRooms[cr-1] and workspace.CurrentRooms[cr-1].Door.Door if OD then ESPLibrary:RemoveESP(OD) end local Doo=workspace.CurrentRooms[cr+1] and workspace.CurrentRooms[cr+1].Door.Door if Doo then AddESP(Doo,"Door "..Doo.Parent:GetAttribute("RoomID"),DoorColor) end end if Toggles.GateLever.Value then local L=workspace.CurrentRooms[cr] and workspace.CurrentRooms[cr]:FindFirstChild("LeverForGate",true) if L then AddESP(L,"Gate Lever",LeverColor) end end if Toggles.Objective.Value then local Key=workspace.CurrentRooms[cr] and workspace.CurrentRooms[cr]:FindFirstChild("KeyObtain",true) if Key then AddESP(Key,"Key",ItemsColor) end end end))

Notify("Doors","Loaded for "..(isBricks and "Backdoor" or CurrentFloor))
