local Cora = getgenv().Cora
assert(Cora and Cora.Library, "[Cora] Library missing - loader failed")
local Library, ThemeManager, SaveManager = Cora.Library, Cora.ThemeManager, Cora.SaveManager
local Options, Toggles = Library.Options, Library.Toggles

local Players=game:GetService('Players')
local UserInputService=game:GetService('UserInputService')
local RunService=game:GetService('RunService')
local HttpService=game:GetService('HttpService')
local ReplicatedStorage=game:GetService('ReplicatedStorage')
local Lighting=game:GetService('Lighting')
local PathfindingService=game:GetService('PathfindingService')
local Debris=game:GetService('Debris')
local localPlayer=Players.LocalPlayer
local camera=workspace.CurrentCamera

local gameName=Cora.gameName
local titleMap={arsenal='Arsenal',nights='99 Nights in the Forest',doors='Doors',unsupported='Unsupported'}
local windowTitle='Cora - '..(titleMap[gameName] or 'Unsupported')
local configFolder='CoraHub/'..tostring(game.PlaceId)

local character=localPlayer.Character or localPlayer.CharacterAdded:Wait()
local humanoid=character:WaitForChild('Humanoid')
local rootPart=character:WaitForChild('HumanoidRootPart')
localPlayer.CharacterAdded:Connect(function(c) character=c humanoid=c:WaitForChild('Humanoid') rootPart=c:WaitForChild('HumanoidRootPart') end)

local Window=Library:CreateWindow({Title=windowTitle,Center=true,AutoShow=true,TabPadding=8,MenuFadeTime=0.2})
local Tabs={}

local UnbindKeys={Enum.KeyCode.Escape,Enum.KeyCode.Backspace,Enum.KeyCode.Home}
local function isUnbindKey(kc) for _,k in ipairs(UnbindKeys) do if k==kc then return true end end return false end
local function getScreenCenter() return Vector2.new(camera.ViewportSize.X/2,camera.ViewportSize.Y/2) end
local function w2v(pos) local sp,on=camera:WorldToViewportPoint(pos) return Vector2.new(sp.X,sp.Y),on,sp.Z end
local function notify(t,m) Library:Notify(t..': '..m,4) end
local function nameContains(name,kw) local low=name:lower() for _,k in ipairs(kw) do if low:find(k:lower(),1,true) then return true end end return false end
local function isValidEnemy(player,tc) if player==localPlayer then return false end local c=player.Character if not c then return false end local h=c:FindFirstChildOfClass('Humanoid') if not h or h.Health<=0 then return false end if not c:FindFirstChild('HumanoidRootPart') then return false end if tc and Library.Toggles[tc] and Library.Toggles[tc].Value then if player.Team and localPlayer.Team and player.Team==localPlayer.Team then return false end end return true end
local Options=Library.Options local Toggles=Library.Toggles
local function makeKeyPicker(gb,text,idx,onOn,onOff) local lbl=gb:AddLabel(text) lbl:AddKeyPicker(idx,{Default='None',Mode='Toggle',Text=text,NoUI=false,ChangedCallback=function(new) if typeof(new)=='EnumItem' and new.EnumType==Enum.KeyCode then if isUnbindKey(new) then Options[idx]:SetValue({'None',Options[idx].Mode or 'Toggle'}) end end end}) Options[idx]:OnClick(function() if Options[idx].Mode=='Toggle' then if Options[idx]:GetState() then onOn() else onOff() end end end) Library:GiveSignal(RunService.Heartbeat:Connect(function() if Options[idx] and Options[idx].Mode=='Hold' then if Options[idx]:GetState() then onOn() else onOff() end end end)) return lbl end

local SKEL={{'Head','UpperTorso'},{'UpperTorso','LowerTorso'},{'UpperTorso','LeftUpperArm'},{'LeftUpperArm','LeftLowerArm'},{'LeftLowerArm','LeftHand'},{'UpperTorso','RightUpperArm'},{'RightUpperArm','RightLowerArm'},{'RightLowerArm','RightHand'},{'LowerTorso','LeftUpperLeg'},{'LeftUpperLeg','LeftLowerLeg'},{'LeftLowerLeg','LeftFoot'},{'LowerTorso','RightUpperLeg'},{'RightUpperLeg','RightLowerLeg'},{'RightLowerLeg','RightFoot'}}
local function newD(t,p) local d=Drawing.new(t) for k,v in pairs(p) do d[k]=v end return d end
local function makeESPObj(label) return {drawings={boxOutline=newD('Square',{Visible=false,Filled=false,Thickness=3,Color=Color3.new(0,0,0)}),box=newD('Square',{Visible=false,Filled=false,Thickness=1}),name=newD('Text',{Visible=false,Size=13,Center=true,Outline=true,Text=label or ''}),hpBg=newD('Square',{Visible=false,Filled=true,Color=Color3.new(0,0,0)}),hp=newD('Square',{Visible=false,Filled=true}),tracer=newD('Line',{Visible=false,Thickness=1})},skel=(function() local t={} for i=1,#SKEL do t[i]=newD('Line',{Visible=false,Thickness=1}) end return t end)()} end
local function hideObj(o) for _,d in pairs(o.drawings) do d.Visible=false end for _,l in pairs(o.skel) do l.Visible=false end end
local function renderObj(o,rp,hp_,label,hp,maxHp,color,trCol,skCol,sBox,sName,sHp,sTr,sSkel,char) local rsp,ron,depth=w2v(rp) local hsp,hon=w2v(hp_) if not ron or not hon or depth<=0 then hideObj(o) return end local h=math.abs(rsp.Y-hsp.Y) local w=h*0.65 local bx=rsp.X-w/2 local by=hsp.Y if sBox then o.drawings.boxOutline.Size=Vector2.new(w+2,h+2) o.drawings.boxOutline.Position=Vector2.new(bx-1,by-1) o.drawings.boxOutline.Visible=true o.drawings.box.Size=Vector2.new(w,h) o.drawings.box.Position=Vector2.new(bx,by) o.drawings.box.Color=color o.drawings.box.Visible=true else o.drawings.box.Visible=false o.drawings.boxOutline.Visible=false end if sName then o.drawings.name.Position=Vector2.new(rsp.X,hsp.Y-16) o.drawings.name.Color=color o.drawings.name.Visible=true else o.drawings.name.Visible=false end if sHp and hp and maxHp then local pct=math.clamp(hp/math.max(maxHp,1),0,1) local barH=h*pct local barX=bx-6 o.drawings.hpBg.Size=Vector2.new(4,h) o.drawings.hpBg.Position=Vector2.new(barX,by) o.drawings.hpBg.Visible=true o.drawings.hp.Size=Vector2.new(4,barH) o.drawings.hp.Position=Vector2.new(barX,by+(h-barH)) o.drawings.hp.Color=Color3.fromRGB((1-pct)*255,pct*255,0) o.drawings.hp.Visible=true else o.drawings.hpBg.Visible=false o.drawings.hp.Visible=false end if sTr then local c=getScreenCenter() o.drawings.tracer.From=Vector2.new(c.X,camera.ViewportSize.Y) o.drawings.tracer.To=rsp o.drawings.tracer.Color=trCol o.drawings.tracer.Visible=true else o.drawings.tracer.Visible=false end if sSkel and char then for i,conn in ipairs(SKEL) do local pA=char:FindFirstChild(conn[1]) local pB=char:FindFirstChild(conn[2]) local ln=o.skel[i] if pA and pB then local spA,onA,dA=w2v(pA.Position) local spB,onB,dB=w2v(pB.Position) if onA and onB and dA>0 and dB>0 then ln.From=spA ln.To=spB ln.Color=skCol ln.Visible=true else ln.Visible=false end else ln.Visible=false end end else for _,l in pairs(o.skel) do l.Visible=false end end end

-- movement (used by arsenal/nights/unsupported)
local wsEnabled=false local defaultWS=16 local customWS=50
local flyEnabled=false local flySpeed=50 local flyBV,flyBG,flyConn=nil,nil,nil
local freecamEnabled=false local fcSpeed=20 local fcConn=nil local fcPitch=0 local fcYaw=0 local savedCamType=nil local isRMB=false
local function startFly() if flyConn then flyConn:Disconnect() flyConn=nil end if flyBV then flyBV:Destroy() end if flyBG then flyBG:Destroy() end flyBV=Instance.new('BodyVelocity') flyBV.Velocity=Vector3.zero flyBV.MaxForce=Vector3.new(1e5,1e5,1e5) flyBV.Parent=rootPart flyBG=Instance.new('BodyGyro') flyBG.MaxTorque=Vector3.new(1e5,1e5,1e5) flyBG.P=1e4 flyBG.Parent=rootPart humanoid.PlatformStand=true flyConn=RunService.Heartbeat:Connect(function() local cam=workspace.CurrentCamera local dir=Vector3.zero if UserInputService:IsKeyDown(Enum.KeyCode.W) then dir+=cam.CFrame.LookVector end if UserInputService:IsKeyDown(Enum.KeyCode.S) then dir-=cam.CFrame.LookVector end if UserInputService:IsKeyDown(Enum.KeyCode.A) then dir-=cam.CFrame.RightVector end if UserInputService:IsKeyDown(Enum.KeyCode.D) then dir+=cam.CFrame.RightVector end if UserInputService:IsKeyDown(Enum.KeyCode.Space) then dir+=Vector3.new(0,1,0) end if UserInputService:IsKeyDown(Enum.KeyCode.LeftShift) then dir-=Vector3.new(0,1,0) end if dir.Magnitude>0 then dir=dir.Unit end flyBV.Velocity=dir*flySpeed flyBG.CFrame=cam.CFrame end) end
local function stopFly() flyEnabled=false if flyConn then flyConn:Disconnect() flyConn=nil end if flyBV then flyBV:Destroy() flyBV=nil end if flyBG then flyBG:Destroy() flyBG=nil end if humanoid then humanoid.PlatformStand=false end if Toggles.FlyToggle then Toggles.FlyToggle:SetValue(false) end end
local function startFreecam() local cam=workspace.CurrentCamera savedCamType=cam.CameraType cam.CameraType=Enum.CameraType.Scriptable if rootPart then local hcf=rootPart.CFrame*CFrame.new(0,1.5,0) cam.CFrame=hcf local lv=hcf.LookVector fcPitch=math.asin(math.clamp(lv.Y,-1,1)) fcYaw=math.atan2(-lv.X,-lv.Z) end if humanoid then humanoid.WalkSpeed=0 humanoid.JumpPower=0 end fcConn=RunService.RenderStepped:Connect(function(dt) if not freecamEnabled then return end local c=workspace.CurrentCamera if isRMB then UserInputService.MouseBehavior=Enum.MouseBehavior.LockCurrentPosition local d=UserInputService:GetMouseDelta() fcYaw-=d.X*0.004 fcPitch=math.clamp(fcPitch-d.Y*0.004,-math.pi/2+0.01,math.pi/2-0.01) else UserInputService.MouseBehavior=Enum.MouseBehavior.Default end local rot=CFrame.Angles(0,fcYaw,0)*CFrame.Angles(fcPitch,0,0) local dir=Vector3.zero if UserInputService:IsKeyDown(Enum.KeyCode.W) then dir+=rot.LookVector end if UserInputService:IsKeyDown(Enum.KeyCode.S) then dir-=rot.LookVector end if UserInputService:IsKeyDown(Enum.KeyCode.A) then dir-=rot.RightVector end if UserInputService:IsKeyDown(Enum.KeyCode.D) then dir+=rot.RightVector end if UserInputService:IsKeyDown(Enum.KeyCode.E) then dir+=Vector3.new(0,1,0) end if UserInputService:IsKeyDown(Enum.KeyCode.Q) then dir-=Vector3.new(0,1,0) end if dir.Magnitude>0 then dir=dir.Unit end c.CFrame=CFrame.new(c.CFrame.Position+dir*fcSpeed*dt)*rot end) end
local function stopFreecam() freecamEnabled=false isRMB=false UserInputService.MouseBehavior=Enum.MouseBehavior.Default if fcConn then fcConn:Disconnect() fcConn=nil end if humanoid then humanoid.WalkSpeed=wsEnabled and customWS or defaultWS humanoid.JumpPower=50 end local cam=workspace.CurrentCamera if savedCamType then cam.CameraType=savedCamType end if Toggles.FreecamToggle then Toggles.FreecamToggle:SetValue(false) end end
UserInputService.InputBegan:Connect(function(i) if i.UserInputType==Enum.UserInputType.MouseButton2 then isRMB=true end end)
UserInputService.InputEnded:Connect(function(i) if i.UserInputType==Enum.UserInputType.MouseButton2 then isRMB=false if not freecamEnabled then UserInputService.MouseBehavior=Enum.MouseBehavior.Default end end end)

local fovCircle=Drawing.new('Circle') fovCircle.Visible=false fovCircle.Radius=120 fovCircle.Color=Color3.fromRGB(255,255,255) fovCircle.Thickness=1 fovCircle.Filled=false fovCircle.NumSides=64
local aimbotActive=false

Tabs.NTTMain=Window:AddTab('Main') Tabs.NTTBring=Window:AddTab('Bring') Tabs.NTTTeleport=Window:AddTab('Teleport') Tabs.NTTVisuals=Window:AddTab('Visuals')
local CAMPFIRE_POS=Vector3.new(0,10,0) local SCRAPPER_POS=Vector3.new(16.1,4,-4.6)
local CHILD_NAMES={'Lost Child','Lost Child2','Lost Child3','Lost Child4'} local CULTIST_KW={'Cultist','Crossbow Cultist'} local ENEMY_ONLY_KW={'Deer','Owl','Ram'} local BUSH_KW={'Bush','BerryBush','Shrub'}
local function isBush(n) return nameContains(n,BUSH_KW) end local function isChild(n) for _,c in ipairs(CHILD_NAMES) do if n==c then return true end end return false end
local function activatePhysics(part) pcall(function() part.Anchored=false part.AssemblyLinearVelocity=Vector3.new(0,0.1,0) end) local m=part.Parent if m and m:IsA('Model') then for _,p in ipairs(m:GetDescendants()) do if p:IsA('BasePart') then pcall(function() p.Anchored=false p.AssemblyLinearVelocity=Vector3.new(0,0.1,0) end) end end end end
local instInt=false local instConn=nil
local function startInst() if instConn then instConn:Disconnect() end instConn=RunService.Heartbeat:Connect(function() if not instInt or not rootPart then return end for _,pp in ipairs(workspace:GetDescendants()) do if pp:IsA('ProximityPrompt') and pp.Enabled then local pt=pp.Parent if pt and pt:IsA('BasePart') and (rootPart.Position-pt.Position).Magnitude<=(pp.MaxActivationDistance+5) then pcall(function() fireproximityprompt(pp) end) end end end end) end
local autoFire=false local FUEL={'Coal','Log','Oil Barrel','Fuel Canister','Biofuel'}
local function getLevel() for _,o in ipairs(workspace:GetDescendants()) do if (o.Name=='Level' or o.Name=='FireLevel') and (o:IsA('IntValue') or o:IsA('NumberValue')) then return o.Value end end return nil end
task.spawn(function() while true do task.wait(1) if not autoFire then continue end local lv=getLevel() if lv and lv>=6 then notify('Auto Campfire','Max level! Pausing.') repeat task.wait(5) until not autoFire or (getLevel() or 6)<6 continue end local f=0 for _,o in ipairs(workspace:GetDescendants()) do if not autoFire then break end if not o:IsA('Model') or isBush(o.Name) then continue end local fuel=false for _,fn in ipairs(FUEL) do if o.Name==fn then fuel=true break end end if not fuel then continue end local pt=o:FindFirstChildWhichIsA('BasePart') if not pt then continue end pcall(function() pt.CFrame=CFrame.new(CAMPFIRE_POS+Vector3.new(math.random(-2,2)*0.3,0,math.random(-2,2)*0.3)) activatePhysics(pt) end) f+=1 task.wait(0.05) end if f>0 then notify('Auto Campfire','Sent '..f..' fuel!') end task.wait(3) end end)
local ITEM_MAP={['Coal']='Coal',['Oil Barrel']='Oil Barrel',['Fuel Canister']='Fuel Canister',['Biofuel']='Biofuel',['Log']='Log',['Sapling']='Sapling',['Chair']='Chair',['Broken Fan']='Broken Fan',['Sheet Metal']='Sheet Metal',['Bolt']='Bolt',['Metal Chair']='Metal Chair',['Broken Microwave']='Broken Microwave',['Old Car Engine']='Old Car Engine',['Old Radio']='Old Radio',['Washing Machine']='Washing Machine',['Cultist Gem']='Cultist Gem',['Tire']='Tyre',['Gem of the Forest Fragment']='Gem of the Forest Fragment',['UFO Junk']='UFO Junk',['UFO Component']='UFO Component',['Morsel']='Morsel',['Cooked Morsel']='Cooked Morsel',['Steak']='Steak',['Cooked Steak']='Cooked Steak',['Berry']='Berry',['Carrot']='Carrot',['Cake']='Cake',['Chili']='Chilli',['Stew']='Stew',['Old Flashlight']='Old Flashlight',['Strong Flashlight']='Strong Flashlight',['Good Axe']='Good Axe',['Strong Axe']='Strong Axe',['Chainsaw']='Chainsaw',['Good Sack']='Good Sack',['Giant Sack']='Giant Sack',['Kunai']='Kunai',['Morningstar']='Morningstar',['Wildfire']='Wildfire',['Infernal Sack']='Infernal Sack',['Defense Blueprint']='Defense Blueprint',['Bear Trap Blueprint']='Bear Trap Blueprint',['Lava Mine Blueprint']='Lava Mine Blueprint',['Medkit']='Medkit',['Bandage']='Bandage',['Spear']='Spear',['Poison Spear']='Poison Spear',['Thorn Body']='Thorn Body',['Obsidiron Body']='Obsidiron Body',['Obsidiron Hammer']='Obsidiron Hammer',['Obsidiron Boots']='Obsidiron Boots',['Cultist King Mace']='Cultist King Mace',['Revolver']='Revolver',['Revolver Ammo']='Revolver Ammo',['Rifle']='Rifle',['Rifle Ammo']='Rifle Ammo',['Tactical Shotgun']='Tactical Shotgun',['Raygun']='Raygun',['Laser Canon']='Laser Canon',['Crossbow']='Crossbow',['Infernal Crossbow']='Infernal Crossbow',['Leather Body']='Leather Body',['Iron Body']='Iron Body',['Alien Armor']='Alien Armor'}
local bringSel={}
local function dropPos(d) if d=='Scrapper' then return Vector3.new(SCRAPPER_POS.X,SCRAPPER_POS.Y+3,SCRAPPER_POS.Z) end if d=='Fire' then return CAMPFIRE_POS+Vector3.new(0,2,0) end return rootPart and (rootPart.Position+Vector3.new(0,5,0)) or Vector3.new(0,100,0) end
local function bring(d) notify('Bring','Searching...') task.spawn(function() local f=0 for _,o in ipairs(workspace:GetDescendants()) do if not o:IsA('Model') or isBush(o.Name) then continue end for dn,inm in pairs(ITEM_MAP) do if not bringSel[dn] then continue end if o.Name==inm then local pt=o:IsA('BasePart') and o or o:FindFirstChildWhichIsA('BasePart') if pt then local dp=dropPos(d) pcall(function() pt.CFrame=CFrame.new(dp+Vector3.new(math.random(-1,1)*0.4,0,math.random(-1,1)*0.4)) activatePhysics(pt) end) f+=1 task.wait(0.03) end break end end end if f==0 then notify('Bring','No items found!') else notify('Bring','Brought '..f..' item(s).') end end) end
local autoChild=false local SCOUT={Vector3.new(0,5,0),Vector3.new(50,5,0),Vector3.new(-50,5,0),Vector3.new(0,5,50),Vector3.new(0,5,-50),Vector3.new(100,5,0),Vector3.new(-100,5,0),Vector3.new(0,5,100),Vector3.new(0,5,-100),Vector3.new(70,5,70),Vector3.new(-70,5,70),Vector3.new(70,5,-70),Vector3.new(-70,5,-70)}
local function doChildren() local found={} local function collect() for _,o in ipairs(workspace:GetDescendants()) do if isChild(o.Name) and o:IsA('Model') then local a=false for _,fc in ipairs(found) do if fc==o then a=true break end end if not a then table.insert(found,o) end end end end collect() if #found==0 then notify('Children','Scouting map...') for _,pos in ipairs(SCOUT) do if not autoChild then return end pcall(function() rootPart.CFrame=CFrame.new(pos) end) task.wait(0.4) collect() end end if #found==0 then notify('Children','No children found!') return end notify('Children','Found '..#found..'!') for _,c in ipairs(found) do if not autoChild then break end local r=c:FindFirstChild('HumanoidRootPart') or c:FindFirstChildWhichIsA('BasePart') if not r then continue end notify('Children','Going to: '..c.Name) pcall(function() rootPart.CFrame=CFrame.new(r.Position+Vector3.new(0,3,0)) end) task.wait(0.4) for _,pp in ipairs(c:GetDescendants()) do if pp:IsA('ProximityPrompt') then pcall(function() fireproximityprompt(pp) end) task.wait(0.15) end end task.wait(0.3) notify('Children','At campfire! Drop manually.') pcall(function() rootPart.CFrame=CFrame.new(CAMPFIRE_POS) end) task.wait(2) end notify('Children','Complete!') end
task.spawn(function() while true do task.wait(5) if autoChild then task.spawn(doChildren) task.wait(15) end end end)
local nttESP={} local nttPlr={}
local function rmN(k) local o=nttESP[k] if not o then return end for _,d in pairs(o.drawings) do pcall(function() d:Remove() end) end for _,l in pairs(o.skel) do pcall(function() l:Remove() end) end nttESP[k]=nil end
Library:GiveSignal(RunService.RenderStepped:Connect(function() local sc=Toggles.NTTChildESP and Toggles.NTTChildESP.Value local sp=Toggles.NTTPlayerESP and Toggles.NTTPlayerESP.Value local se=Toggles.NTTEnemyESP and Toggles.NTTEnemyESP.Value local scu=Toggles.NTTCultistESP and Toggles.NTTCultistESP.Value local cC=Options.NTTChildColor and Options.NTTChildColor.Value or Color3.fromRGB(100,255,150) local pC=Options.NTTPlayerColor and Options.NTTPlayerColor.Value or Color3.fromRGB(50,150,255) local eC=Options.NTTEnemyColor and Options.NTTEnemyColor.Value or Color3.fromRGB(255,100,50) local cuC=Options.NTTCultistColor and Options.NTTCultistColor.Value or Color3.fromRGB(200,50,255) local tr=Toggles.NTTTracer and Toggles.NTTTracer.Value local chars=workspace:FindFirstChild('Characters') local active={} if chars then for _,npc in ipairs(chars:GetChildren()) do active[npc]=true local iC=isChild(npc.Name) local iCu=nameContains(npc.Name,CULTIST_KW) local iE=nameContains(npc.Name,ENEMY_ONLY_KW) local show=(sc and iC) or (scu and iCu) or (se and iE) if not show then if nttESP[npc] then hideObj(nttESP[npc]) end continue end if not nttESP[npc] then nttESP[npc]=makeESPObj(npc.Name) end local o=nttESP[npc] local r=npc:FindFirstChild('HumanoidRootPart') or npc:FindFirstChildWhichIsA('BasePart') local hd=npc:FindFirstChild('Head') or r local h=npc:FindFirstChildOfClass('Humanoid') if not r or not hd then hideObj(o) continue end local col=iC and cC or (iCu and cuC or eC) renderObj(o,r.Position,hd.Position+Vector3.new(0,0.7,0),npc.Name,h and h.Health,h and h.MaxHealth,col,col,col,true,true,h~=nil,tr,false,npc) end end for k in pairs(nttESP) do if not active[k] then rmN(k) end end for _,plr in ipairs(Players:GetPlayers()) do if plr==localPlayer then continue end if not sp then if nttPlr[plr] then hideObj(nttPlr[plr]) end continue end if not nttPlr[plr] then nttPlr[plr]=makeESPObj(plr.Name) end local o=nttPlr[plr] local c=plr.Character local r=c and c:FindFirstChild('HumanoidRootPart') local hd=c and c:FindFirstChild('Head') local h=c and c:FindFirstChildOfClass('Humanoid') if not r or not hd or not h then hideObj(o) continue end renderObj(o,r.Position,hd.Position+Vector3.new(0,0.7,0),plr.Name,h.Health,h.MaxHealth,pC,pC,pC,true,true,true,tr,false,c) end end))
local InteractBox=Tabs.NTTMain:AddLeftGroupbox('Interact') local FireBox=Tabs.NTTMain:AddRightGroupbox('Campfire') local ChildBox=Tabs.NTTMain:AddRightGroupbox('Children')
InteractBox:AddToggle('NTTInstantInteract',{Text='Instant Interact',Default=false,Callback=function(v) instInt=v if v then startInst() else if instConn then instConn:Disconnect() instConn=nil end end end})
FireBox:AddToggle('NTTAutoCampfire',{Text='Auto Campfire',Default=false,Callback=function(v) autoFire=v end})
ChildBox:AddToggle('NTTAutoChildren',{Text='Auto Get Children',Default=false,Callback=function(v) autoChild=v end})
ChildBox:AddButton({Text='Run Now',Func=function() task.spawn(doChildren) end})
local BringLeft=Tabs.NTTBring:AddLeftGroupbox('Items') local BringRight=Tabs.NTTBring:AddRightGroupbox('Options')
BringRight:AddDropdown('NTTBringDest',{Text='Drop to',Values={'Player','Scrapper','Fire'},Default=1})
BringRight:AddButton({Text='Bring Selected',Func=function() bring(Options.NTTBringDest and Options.NTTBringDest.Value or 'Player') end})
BringRight:AddButton({Text='Select All',Func=function() for k in pairs(bringSel) do bringSel[k]=true local i='NTTBring_'..k:gsub('%W','_') if Toggles[i] then Toggles[i]:SetValue(true) end end end})
BringRight:AddButton({Text='Deselect All',Func=function() for k in pairs(bringSel) do bringSel[k]=false local i='NTTBring_'..k:gsub('%W','_') if Toggles[i] then Toggles[i]:SetValue(false) end end end})
local CATS={{name='Fuel',items={'Coal','Oil Barrel','Fuel Canister','Biofuel'}},{name='Wood',items={'Log','Sapling','Chair'}},{name='Scrap',items={'Broken Fan','Sheet Metal','Bolt','Metal Chair','Broken Microwave','Old Car Engine','Old Radio','Washing Machine','Cultist Gem','Tire','Gem of the Forest Fragment','UFO Junk','UFO Component'}},{name='Food',items={'Morsel','Cooked Morsel','Steak','Cooked Steak','Berry','Carrot','Cake','Chili','Stew'}},{name='Tool',items={'Old Flashlight','Strong Flashlight','Good Axe','Strong Axe','Chainsaw','Good Sack','Giant Sack','Kunai','Morningstar','Wildfire','Infernal Sack','Defense Blueprint','Bear Trap Blueprint','Lava Mine Blueprint','Medkit','Bandage','Spear','Poison Spear','Thorn Body','Obsidiron Body','Obsidiron Hammer','Obsidiron Boots','Cultist King Mace'}},{name='Gun',items={'Revolver','Revolver Ammo','Rifle','Rifle Ammo','Tactical Shotgun','Raygun','Laser Canon','Crossbow','Infernal Crossbow','Leather Body','Iron Body','Alien Armor'}}}
for _,cat in ipairs(CATS) do BringLeft:AddLabel(cat.name) for _,item in ipairs(cat.items) do local i='NTTBring_'..item:gsub('%W','_') bringSel[item]=false BringLeft:AddToggle(i,{Text=item,Default=false,Callback=function(v) bringSel[item]=v end}) end BringLeft:AddDivider() end
local TeleBox=Tabs.NTTTeleport:AddLeftGroupbox('Teleport')
TeleBox:AddButton({Text='Teleport to Fire',Func=function() if rootPart then rootPart.CFrame=CFrame.new(CAMPFIRE_POS) notify('Teleport','To Campfire!') end end})
TeleBox:AddButton({Text='Teleport to Scrapper',Func=function() if rootPart then rootPart.CFrame=CFrame.new(SCRAPPER_POS+Vector3.new(0,5,0)) notify('Teleport','To Scrapper!') end end})
local vc=Tabs.NTTVisuals:AddLeftGroupbox('Children ESP') vc:AddToggle('NTTChildESP',{Text='Enable',Default=false}) vc:AddLabel('Color'):AddColorPicker('NTTChildColor',{Default=Color3.fromRGB(100,255,150),Title='Children'})
local vp=Tabs.NTTVisuals:AddRightGroupbox('Player ESP') vp:AddToggle('NTTPlayerESP',{Text='Enable',Default=false}) vp:AddLabel('Color'):AddColorPicker('NTTPlayerColor',{Default=Color3.fromRGB(50,150,255),Title='Players'})
local ve=Tabs.NTTVisuals:AddLeftGroupbox('Enemy ESP') ve:AddToggle('NTTEnemyESP',{Text='Enable (Deer/Owl/Ram)',Default=false}) ve:AddLabel('Color'):AddColorPicker('NTTEnemyColor',{Default=Color3.fromRGB(255,100,50),Title='Enemy'})
local vcu=Tabs.NTTVisuals:AddRightGroupbox('Cultist ESP') vcu:AddToggle('NTTCultistESP',{Text='Enable',Default=false}) vcu:AddLabel('Color'):AddColorPicker('NTTCultistColor',{Default=Color3.fromRGB(200,50,255),Title='Cultist'})
local vt=Tabs.NTTVisuals:AddLeftGroupbox('Shared') vt:AddToggle('NTTTracer',{Text='Tracers',Default=false})

-- ===== SETTINGS FOOTER (paste at end of every module) =====
Tabs.Settings=Window:AddTab('Settings')
local MenuBox=Tabs.Settings:AddLeftGroupbox('Menu') local ThemeBox=Tabs.Settings:AddLeftGroupbox('Theme')
MenuBox:AddLabel('UI Toggle Key'):AddKeyPicker('MenuKeybind',{Default='P',NoUI=true,Text='UI Toggle Key'})
Library.ToggleKeybind=Options.MenuKeybind
MenuBox:AddButton({Text='Unload',Func=function() pcall(function() fovCircle:Remove() end) Library:Unload() end})
ThemeManager.BuiltInThemes['Cora']={1,HttpService:JSONDecode('{"FontColor":"ffffff","MainColor":"1a1a2e","AccentColor":"e8e8ff","BackgroundColor":"0f0f1a","OutlineColor":"2a2a4a"}')}
ThemeManager:SetLibrary(Library) ThemeManager:SetFolder('CoraHub') ThemeManager:ApplyToGroupbox(ThemeBox)
SaveManager:SetLibrary(Library) SaveManager:IgnoreThemeSettings() SaveManager:SetIgnoreIndexes({'MenuKeybind'})
SaveManager:SetFolder(configFolder) SaveManager:BuildConfigSection(Tabs.Settings)
ThemeManager:ApplyTheme('Cora') SaveManager:LoadAutoloadConfig()
